// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: cart.proto

package cartrpc

import (
	"context"

	"shop/cart/cart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddToCartRequest   = cart.AddToCartRequest
	AddToCartResponse  = cart.AddToCartResponse
	CartItem           = cart.CartItem
	ClearCartRequest   = cart.ClearCartRequest
	ClearCartResponse  = cart.ClearCartResponse
	GetCartRequest     = cart.GetCartRequest
	GetCartResponse    = cart.GetCartResponse
	UpdateCartRequest  = cart.UpdateCartRequest
	UpdateCartResponse = cart.UpdateCartResponse

	CartRpc interface {
		AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
		GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error)
		UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*UpdateCartResponse, error)
		ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*ClearCartResponse, error)
	}

	defaultCartRpc struct {
		cli zrpc.Client
	}
)

func NewCartRpc(cli zrpc.Client) CartRpc {
	return &defaultCartRpc{
		cli: cli,
	}
}

func (m *defaultCartRpc) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.AddToCart(ctx, in, opts...)
}

func (m *defaultCartRpc) GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.GetCart(ctx, in, opts...)
}

func (m *defaultCartRpc) UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*UpdateCartResponse, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.UpdateCart(ctx, in, opts...)
}

func (m *defaultCartRpc) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*ClearCartResponse, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.ClearCart(ctx, in, opts...)
}
