// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: cart.proto

package server

import (
	"context"

	"shop/cart/cart"
	"shop/cart/internal/logic"
	"shop/cart/internal/svc"
)

type CartRpcServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartRpcServer
}

func NewCartRpcServer(svcCtx *svc.ServiceContext) *CartRpcServer {
	return &CartRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *CartRpcServer) AddToCart(ctx context.Context, in *cart.AddToCartRequest) (*cart.AddToCartResponse, error) {
	l := logic.NewAddToCartLogic(ctx, s.svcCtx)
	return l.AddToCart(in)
}

func (s *CartRpcServer) GetCart(ctx context.Context, in *cart.GetCartRequest) (*cart.GetCartResponse, error) {
	l := logic.NewGetCartLogic(ctx, s.svcCtx)
	return l.GetCart(in)
}

func (s *CartRpcServer) UpdateCart(ctx context.Context, in *cart.UpdateCartRequest) (*cart.UpdateCartResponse, error) {
	l := logic.NewUpdateCartLogic(ctx, s.svcCtx)
	return l.UpdateCart(in)
}

func (s *CartRpcServer) ClearCart(ctx context.Context, in *cart.ClearCartRequest) (*cart.ClearCartResponse, error) {
	l := logic.NewClearCartLogic(ctx, s.svcCtx)
	return l.ClearCart(in)
}
