// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentsFieldNames          = builder.RawFieldNames(&Payments{})
	paymentsRows                = strings.Join(paymentsFieldNames, ",")
	paymentsRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	paymentsRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	paymentsModel interface {
		Insert(ctx context.Context, data *Payments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Payments, error)
		FindOneByPaymentId(ctx context.Context, paymentId string) (*Payments, error)
		Update(ctx context.Context, data *Payments) error
		UpdateStatus(ctx context.Context, paymentId, status, transactionId string) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPaymentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Payments struct {
		Id            int64          `db:"id"`
		PaymentId     string         `db:"payment_id"`
		OrderId       string         `db:"order_id"`
		UserId        string         `db:"user_id"`
		Amount        float64        `db:"amount"`
		PaymentMethod string         `db:"payment_method"`
		Status        string         `db:"status"`
		TransactionId sql.NullString `db:"transaction_id"`
		CreatedAt     time.Time      `db:"created_at"`
		UpdatedAt     time.Time      `db:"updated_at"`
	}
)

func newPaymentsModel(conn sqlx.SqlConn) *defaultPaymentsModel {
	return &defaultPaymentsModel{
		conn:  conn,
		table: "`payments`",
	}
}

func (m *defaultPaymentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPaymentsModel) FindOne(ctx context.Context, id int64) (*Payments, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", paymentsRows, m.table)
	var resp Payments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentsModel) FindOneByPaymentId(ctx context.Context, paymentId string) (*Payments, error) {
	var resp Payments
	query := fmt.Sprintf("select %s from %s where `payment_id` = ? limit 1", paymentsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, paymentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentsModel) Insert(ctx context.Context, data *Payments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, paymentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PaymentId, data.OrderId, data.UserId, data.Amount, data.PaymentMethod, data.Status, data.TransactionId)
	return ret, err
}

func (m *defaultPaymentsModel) Update(ctx context.Context, newData *Payments) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, paymentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PaymentId, newData.OrderId, newData.UserId, newData.Amount, newData.PaymentMethod, newData.Status, newData.TransactionId, newData.Id)
	return err
}

func (m *defaultPaymentsModel) UpdateStatus(ctx context.Context, paymentId, status, transactionId string) error {
	query := fmt.Sprintf("update %s set status=? where `payment_id` = ? and `transaction_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, status, paymentId, transactionId)
	return err
}

func (m *defaultPaymentsModel) tableName() string {
	return m.table
}
