Name: product
Host: 0.0.0.0
ListenOn: 0.0.0.0:9082
Mysql:
  DataSource: root:password@tcp(localhost:3306)/shop?charset=utf8mb4&parseTime=true
Redis:
  Host: 127.0.0.1:6379
  Key: product
  Pass: nU(8auUJZs6C
Jwt:
  AccessSecret: your-secret-key
  AccessExpire: 604800
Telemetry:
  Metrics:  # 这是新版 go-zero 推荐的方式
    Enabled: false