// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=PaymentMethod,proto3" json:"PaymentMethod,omitempty"` // wechat, alipay
	Status        string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`               // pending, completed, failed
	TransactionId string                 `protobuf:"bytes,7,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Refund struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=RefundId,proto3" json:"RefundId,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"` // pending, completed, failed
	TransactionId string                 `protobuf:"bytes,7,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refund) Reset() {
	*x = Refund{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refund) ProtoMessage() {}

func (x *Refund) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refund.ProtoReflect.Descriptor instead.
func (*Refund) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Refund) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *Refund) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Refund) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Refund) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Refund) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Refund) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Refund) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Refund) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Refund) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=PaymentMethod,proto3" json:"PaymentMethod,omitempty"` // wechat, alipay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=PaymentUrl,proto3" json:"PaymentUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=Payment,proto3" json:"Payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentStatusResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"` // completed, failed
	Sign          string                 `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`     // 回调签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentCallbackRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentCallbackRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type PaymentCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackResponse) Reset() {
	*x = PaymentCallbackResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackResponse) ProtoMessage() {}

func (x *PaymentCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackResponse.ProtoReflect.Descriptor instead.
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=PaymentId,proto3" json:"PaymentId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=Amount,proto3" json:"Amount,omitempty"` // 退款金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=RefundId,proto3" json:"RefundId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *RefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

type GetRefundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=RefundId,proto3" json:"RefundId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundStatusRequest) Reset() {
	*x = GetRefundStatusRequest{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundStatusRequest) ProtoMessage() {}

func (x *GetRefundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRefundStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *GetRefundStatusRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *GetRefundStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRefundStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refund        *Refund                `protobuf:"bytes,1,opt,name=Refund,proto3" json:"Refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefundStatusResponse) Reset() {
	*x = GetRefundStatusResponse{}
	mi := &file_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefundStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefundStatusResponse) ProtoMessage() {}

func (x *GetRefundStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefundStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRefundStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetRefundStatusResponse) GetRefund() *Refund {
	if x != nil {
		return x.Refund
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\x91\x02\n" +
	"\aPayment\x12\x1c\n" +
	"\tPaymentId\x18\x01 \x01(\tR\tPaymentId\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\tR\aOrderId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x01R\x06Amount\x12$\n" +
	"\rPaymentMethod\x18\x05 \x01(\tR\rPaymentMethod\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\tR\x06Status\x12$\n" +
	"\rTransactionId\x18\a \x01(\tR\rTransactionId\x12\x1c\n" +
	"\tCreatedAt\x18\b \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\t \x01(\tR\tUpdatedAt\"\x86\x02\n" +
	"\x06Refund\x12\x1a\n" +
	"\bRefundId\x18\x01 \x01(\tR\bRefundId\x12\x1c\n" +
	"\tPaymentId\x18\x02 \x01(\tR\tPaymentId\x12\x18\n" +
	"\aOrderId\x18\x03 \x01(\tR\aOrderId\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x01R\x06Amount\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\tR\x06Status\x12$\n" +
	"\rTransactionId\x18\a \x01(\tR\rTransactionId\x12\x1c\n" +
	"\tCreatedAt\x18\b \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\t \x01(\tR\tUpdatedAt\"n\n" +
	"\x14CreatePaymentRequest\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\tR\aOrderId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12$\n" +
	"\rPaymentMethod\x18\x03 \x01(\tR\rPaymentMethod\"U\n" +
	"\x15CreatePaymentResponse\x12\x1c\n" +
	"\tPaymentId\x18\x01 \x01(\tR\tPaymentId\x12\x1e\n" +
	"\n" +
	"PaymentUrl\x18\x02 \x01(\tR\n" +
	"PaymentUrl\"O\n" +
	"\x17GetPaymentStatusRequest\x12\x1c\n" +
	"\tPaymentId\x18\x01 \x01(\tR\tPaymentId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"F\n" +
	"\x18GetPaymentStatusResponse\x12*\n" +
	"\aPayment\x18\x01 \x01(\v2\x10.payment.PaymentR\aPayment\"\x88\x01\n" +
	"\x16PaymentCallbackRequest\x12\x1c\n" +
	"\tPaymentId\x18\x01 \x01(\tR\tPaymentId\x12$\n" +
	"\rTransactionId\x18\x02 \x01(\tR\rTransactionId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\x12\x12\n" +
	"\x04Sign\x18\x04 \x01(\tR\x04Sign\"3\n" +
	"\x17PaymentCallbackResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"]\n" +
	"\rRefundRequest\x12\x1c\n" +
	"\tPaymentId\x18\x01 \x01(\tR\tPaymentId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x01R\x06Amount\",\n" +
	"\x0eRefundResponse\x12\x1a\n" +
	"\bRefundId\x18\x01 \x01(\tR\bRefundId\"L\n" +
	"\x16GetRefundStatusRequest\x12\x1a\n" +
	"\bRefundId\x18\x01 \x01(\tR\bRefundId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"B\n" +
	"\x17GetRefundStatusResponse\x12'\n" +
	"\x06Refund\x18\x01 \x01(\v2\x0f.payment.RefundR\x06Refund2\x9c\x03\n" +
	"\n" +
	"PaymentRpc\x12N\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12W\n" +
	"\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponse\x12T\n" +
	"\x0fPaymentCallback\x12\x1f.payment.PaymentCallbackRequest\x1a .payment.PaymentCallbackResponse\x129\n" +
	"\x06Refund\x12\x16.payment.RefundRequest\x1a\x17.payment.RefundResponse\x12T\n" +
	"\x0fGetRefundStatus\x12\x1f.payment.GetRefundStatusRequest\x1a .payment.GetRefundStatusResponseB\vZ\t./paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payment_proto_goTypes = []any{
	(*Payment)(nil),                  // 0: payment.Payment
	(*Refund)(nil),                   // 1: payment.Refund
	(*CreatePaymentRequest)(nil),     // 2: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),    // 3: payment.CreatePaymentResponse
	(*GetPaymentStatusRequest)(nil),  // 4: payment.GetPaymentStatusRequest
	(*GetPaymentStatusResponse)(nil), // 5: payment.GetPaymentStatusResponse
	(*PaymentCallbackRequest)(nil),   // 6: payment.PaymentCallbackRequest
	(*PaymentCallbackResponse)(nil),  // 7: payment.PaymentCallbackResponse
	(*RefundRequest)(nil),            // 8: payment.RefundRequest
	(*RefundResponse)(nil),           // 9: payment.RefundResponse
	(*GetRefundStatusRequest)(nil),   // 10: payment.GetRefundStatusRequest
	(*GetRefundStatusResponse)(nil),  // 11: payment.GetRefundStatusResponse
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: payment.GetPaymentStatusResponse.Payment:type_name -> payment.Payment
	1,  // 1: payment.GetRefundStatusResponse.Refund:type_name -> payment.Refund
	2,  // 2: payment.PaymentRpc.CreatePayment:input_type -> payment.CreatePaymentRequest
	4,  // 3: payment.PaymentRpc.GetPaymentStatus:input_type -> payment.GetPaymentStatusRequest
	6,  // 4: payment.PaymentRpc.PaymentCallback:input_type -> payment.PaymentCallbackRequest
	8,  // 5: payment.PaymentRpc.Refund:input_type -> payment.RefundRequest
	10, // 6: payment.PaymentRpc.GetRefundStatus:input_type -> payment.GetRefundStatusRequest
	3,  // 7: payment.PaymentRpc.CreatePayment:output_type -> payment.CreatePaymentResponse
	5,  // 8: payment.PaymentRpc.GetPaymentStatus:output_type -> payment.GetPaymentStatusResponse
	7,  // 9: payment.PaymentRpc.PaymentCallback:output_type -> payment.PaymentCallbackResponse
	9,  // 10: payment.PaymentRpc.Refund:output_type -> payment.RefundResponse
	11, // 11: payment.PaymentRpc.GetRefundStatus:output_type -> payment.GetRefundStatusResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
