// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddProductRequest struct {
	Name        string  `json:"name"`
	Description string  `json:"description,optional"`
	Detail      string  `json:"detail,optional"`
	MainImage   string  `json:"main_image,optional"`
	Thumbnail   string  `json:"thumbnail,optional"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	CategoryID  int64   `json:"category_id"`
	IsBanner    bool    `json:"is_banner,optional"`
}

type AddProductResponse struct {
	ID int64 `json:"id"`
}

type ChangeAvatarRequest struct {
	UserID    int64  `json:"user_id,optional"` // Populated from JWT
	NewAvatar string `json:"new_avatar"`
}

type ChangeAvatarResponse struct {
	Success bool `json:"success"`
}

type ChangePasswordRequest struct {
	UserID      int64  `json:"user_id,optional"` // Populated from JWT
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Success bool `json:"success"`
}

type ChangeUsernameRequest struct {
	UserID      int64  `json:"user_id,optional"` // Populated from JWT
	NewUsername string `json:"new_username"`
}

type ChangeUsernameResponse struct {
	Success bool `json:"success"`
}

type GetProductDetailRequest struct {
	ID int64 `json:"id"`
}

type GetProductDetailResponse struct {
	Product Product `json:"product"`
}

type GetUserInfoRequest struct {
	UserID int64 `json:"user_id,optional"` // Populated from JWT
}

type GetUserInfoResponse struct {
	UserID    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Bio       string `json:"bio"`
	Address   string `json:"address"`
	CreatedAt string `json:"created_at"`
}

type ListBannerProductsRequest struct {
	Limit int32 `json:"limit" default:"5"`
}

type ListBannerProductsResponse struct {
	Products []Product `json:"products"`
}

type ListProductsRequest struct {
	Page       int32    `json:"page,optional" default:"1"`
	PageSize   int32    `json:"page_size,optional" default:"10"`
	CategoryID *int64   `json:"category_id,optional"`
	MinPrice   *float64 `json:"min_price,optional"`
	MaxPrice   *float64 `json:"max_price,optional"`
}

type ListProductsResponse struct {
	Products []Product `json:"products"`
	Total    int32     `json:"total"`
}

type ListRecommendedProductsRequest struct {
	Limit int32 `json:"limit" default:"5"`
}

type ListRecommendedProductsResponse struct {
	Products []Product `json:"products"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type Product struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Detail      string  `json:"detail"`
	MainImage   string  `json:"main_image"`
	Thumbnail   string  `json:"thumbnail"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	CategoryID  int64   `json:"category_id"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar,optional"`
	Bio      string `json:"bio,optional"`
	Address  string `json:"address,optional"`
}

type RegisterResponse struct {
	UserID int64 `json:"user_id"`
}

type UpdateProductRequest struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name,optional"`
	Description string  `json:"description,optional"`
	Detail      string  `json:"detail,optional"`
	MainImage   string  `json:"main_image,optional"`
	Thumbnail   string  `json:"thumbnail,optional"`
	Price       float64 `json:"price,optional"`
	Stock       int32   `json:"stock,optional"`
	CategoryID  int64   `json:"category_id,optional"`
}

type UpdateProductResponse struct {
	Success bool `json:"success"`
}
