// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddProductRequest struct {
	Name        string  `json:"name"`
	Description string  `json:"description,optional"`
	Detail      string  `json:"detail,optional"`
	MainImage   string  `json:"main_image,optional"`
	Thumbnail   string  `json:"thumbnail,optional"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	CategoryID  string  `json:"category_id"`
	IsBanner    bool    `json:"is_banner,optional"`
	Pid         string  `json:"pid"`
}

type AddProductResponse struct {
	Pid string `json:"pid"`
}

type ChangeAvatarRequest struct {
	UserID    string `json:"user_id,optional"` // Populated from JWT
	NewAvatar string `json:"new_avatar"`
}

type ChangeAvatarResponse struct {
	Success bool `json:"success"`
}

type ChangePasswordRequest struct {
	UserID      string `json:"user_id,optional"` // Populated from JWT
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Success bool `json:"success"`
}

type ChangeRoleRequest struct {
	UserID string `json:"user_id,optional"` // Populated from JWT
	Role   string `json:"role"`
}

type ChangeRoleResponse struct {
	Success bool `json:"success"`
}

type ChangeUsernameRequest struct {
	UserID      string `json:"user_id,optional"` // Populated from JWT
	NewUsername string `json:"new_username"`
}

type ChangeUsernameResponse struct {
	Success bool `json:"success"`
}

type CreateOrderRequest struct {
	UserID string      `json:"user_id,optional"` // 从JWT获取
	Items  []OrderItem `json:"items"`
}

type CreateOrderResponse struct {
	OrderID string `json:"order_id"`
}

type GetOrderDetailRequest struct {
	OrderID string `json:"order_id"`
}

type GetOrderDetailResponse struct {
	Order Order `json:"order"`
}

type GetProductDetailRequest struct {
	Pid string `form:"pid"`
}

type GetProductDetailResponse struct {
	Product Product `json:"product"`
}

type GetUserInfoRequest struct {
	UserID string `form:"user_id,optional"` // Populated from JWT
}

type GetUserInfoResponse struct {
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Bio       string `json:"bio"`
	Address   string `json:"address"`
	CreatedAt string `json:"created_at"`
}

type ListBannerProductsRequest struct {
	Limit int32 `form:"limit" default:"5"`
}

type ListBannerProductsResponse struct {
	Products []Product `json:"products"`
}

type ListOrdersRequest struct {
	UserID   string `json:"user_id,optional"` // 从JWT获取
	Page     int32  `form:"page" default:"1"`
	PageSize int32  `form:"page_size" default:"10"`
}

type ListOrdersResponse struct {
	Orders []Order `json:"orders"`
	Total  int32   `json:"total"`
}

type ListProductsRequest struct {
	Page       int32   `form:"page" default:"1"`
	PageSize   int32   `form:"page_size" default:"10"`
	CategoryID string  `form:"category_id,optional"`
	MinPrice   float64 `form:"min_price,optional"`
	MaxPrice   float64 `form:"max_price,optional"`
}

type ListProductsResponse struct {
	Products []Product `json:"products"`
	Total    int32     `json:"total"`
}

type ListRecommendedProductsRequest struct {
	Limit int32 `form:"limit" default:"5"`
}

type ListRecommendedProductsResponse struct {
	Products []Product `json:"products"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type Order struct {
	OrderID    string      `json:"order_id"`
	UserID     string      `json:"user_id"`
	Items      []OrderItem `json:"items"`
	TotalPrice float64     `json:"total_price"`
	Status     string      `json:"status"` // pending, paid, shipped, cancelled
	CreatedAt  string      `json:"created_at"`
	UpdatedAt  string      `json:"updated_at"`
}

type OrderItem struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type Product struct {
	Pid         string  `json:"pid"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Detail      string  `json:"detail"`
	MainImage   string  `json:"main_image"`
	Thumbnail   string  `json:"thumbnail"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	CategoryID  string  `json:"category_id"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar,optional"`
	Bio      string `json:"bio,optional"`
	Address  string `json:"address,optional"`
}

type RegisterResponse struct {
	UserID string `json:"user_id"`
}

type SeckillOrderRequest struct {
	UserID    string `json:"user_id,optional"` // 从JWT获取
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type SeckillOrderResponse struct {
	OrderID string `json:"order_id"`
	Success bool   `json:"success"`
}

type UpdateOrderStatusRequest struct {
	OrderID string `json:"order_id"`
	Status  string `json:"status"`
}

type UpdateOrderStatusResponse struct {
	Success bool `json:"success"`
}

type UpdateProductRequest struct {
	Pid         string  `json:"pid"`
	Name        string  `json:"name,optional"`
	Description string  `json:"description,optional"`
	Detail      string  `json:"detail,optional"`
	MainImage   string  `json:"main_image,optional"`
	Thumbnail   string  `json:"thumbnail,optional"`
	Price       float64 `json:"price,optional"`
	Stock       int32   `json:"stock,optional"`
	CategoryID  string  `json:"category_id,optional"`
}

type UpdateProductResponse struct {
	Success bool `json:"success"`
}
